---
functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - Сайт должен иметь мобильную версию
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - При отжатой галке "В наличии" показывать все товары независимо от наличия
  - При нажатии на крестик в окне оформления заказа закрывать окно
  - Количество единиц товара в корзине должно быть выровнено друг под другом
  - Название магазина в заголовке страницы должно быть гиперссылкой на главную страницу магазина
  - Должен быть выбор "все категории" в фильтре
